const state={products:[],filter:'all',expanded:false};
const $=s=>document.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function categories(){return [...new Set(state.products.map(p=>p.category).filter(Boolean))]}
function renderFilters(){const el=$('#product-filters');el.innerHTML=['all',...categories()].map((c,i)=>'<button class="filter-btn '+(i===0?'active':'')+'" data-filter="'+esc(c)+'">'+esc(c==='all'?'All designs':c)+'</button>').join('');el.onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;state.filter=b.dataset.filter;state.expanded=state.filter!=='all';renderProducts();renderFilters();}}
function visibleProducts(){return state.filter==='all'?state.products:state.products.filter(p=>p.category===state.filter)}
function renderProducts(){const all=visibleProducts(),limit=state.expanded?all.length:Math.min(all.length,8);const grid=$('#product-grid');grid.innerHTML=all.slice(0,limit).map(p=>'<article class="product-card"><button class="product-image" data-id="'+p.id+'" aria-label="View '+esc(p.title)+'"><img src="'+esc(p.image||p.sourceImage)+'" alt="'+esc(p.title)+'" loading="lazy"></button><div class="product-info"><span class="product-category">'+esc(p.category)+'</span><h3 class="product-title">'+esc(p.title)+'</h3><button class="product-details-btn" data-id="'+p.id+'">View design →</button></div></article>').join('');grid.onclick=e=>{const b=e.target.closest('[data-id]');if(b)openProduct(Number(b.dataset.id))};const more=$('#collection-toggle');if(all.length>8&&state.filter==='all'){more.hidden=false;more.textContent=state.expanded?'Show fewer':'View all '+all.length+' designs'}else more.hidden=true;}
let lastFocus=null;
function openProduct(id){const p=state.products.find(x=>Number(x.id)===id);if(!p)return;$('#modal-photo').src=p.image||p.sourceImage;$('#modal-photo').alt=p.title;$('#modal-category').textContent=p.category;$('#modal-title').textContent=p.title;$('#modal-desc').textContent=p.description||'';$('#modal-wa-btn').href='https://wa.me/918100656258?text='+encodeURIComponent('Hello JHALAR, I am interested in '+p.title+'.');const m=$('#product-modal');lastFocus=document.activeElement;m.classList.add('open');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';$('#modal-close').focus()}
function closeModal(){const m=$('#product-modal');if(!m.classList.contains('open'))return;m.classList.remove('open');m.setAttribute('aria-hidden','true');document.body.style.overflow='';if(lastFocus&&typeof lastFocus.focus==='function')lastFocus.focus();lastFocus=null}
async function initProducts(){try{const gate=window.JHALARNaming;if(!gate)throw Error('Naming gate unavailable');const[pr,nr]=await Promise.all([fetch('content/products.json',{cache:'no-store'}),fetch('content/product-naming.json',{cache:'no-store'})]);if(!pr.ok)throw Error('Catalogue unavailable');if(!nr.ok)throw Error('Naming registry unavailable');const d=await pr.json();const registry=await nr.json();const products=Array.isArray(d.products)?d.products:[];const report=gate.validateCatalogue({products},registry);if(report.errors.length)throw Error('Catalogue rejected by naming gate: '+report.errors[0]);const approved=new Set(report.products.filter(x=>x.status===gate.STATUS.APPROVED&&!x.humanReviewRequired).map(x=>x.productId));state.products=products.filter(p=>approved.has(p.id));if(!state.products.length)throw Error('No approved products in catalogue');renderFilters();renderProducts()}catch(e){console.error(e);$('#product-grid').innerHTML='<p>Products are being updated. Please check back shortly.</p>'}}
$('#collection-toggle').onclick=()=>{state.expanded=!state.expanded;renderProducts();if(!state.expanded)$('#collection').scrollIntoView({behavior:'smooth'})};
$('#menu').onclick=()=>{const b=$('#menu'),n=$('#mobile-nav'),open=!n.classList.contains('open');n.classList.toggle('open',open);b.setAttribute('aria-expanded',String(open))};
$('#mobile-nav').onclick=e=>{if(e.target.matches('a')){$('#mobile-nav').classList.remove('open');$('#menu').setAttribute('aria-expanded','false')}};
document.addEventListener('click',e=>{if(e.target.closest('[data-close]'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});$('#year').textContent=new Date().getFullYear();initProducts();