// JHALAR Hanging Decor — clean runtime
// Canonical runtime data lives in content/*.json.
let products = [];
let settings = {
  whatsapp: '918100656258', phone: '+91 81006 56258', email: 'lokeshdugar040@gmail.com', location: 'Howrah, West Bengal, India', gst: 'Available on request',
  heroHeadline: 'Jhalars and hanging decor for weddings and events',
  heroIntro: 'Browse designs and colour variants and open any design for details.', heroImage: 'assets/images/hero-jhalar.jpg',
  siteTitle: 'JHALAR | Jhalars and Hanging Decor for Weddings and Events',
  siteDescription: 'Browse the JHALAR catalogue of jhalars and hanging decor for weddings and events.', ogImage: 'assets/images/og-cover.jpg',
  navItems: [{label:'Collection',href:'#collection'},{label:'Custom Orders',href:'#custom-orders'},{label:'About',href:'#about'}],
  footerNavItems: [{label:'Collection',href:'#collection'},{label:'Custom Orders',href:'#custom-orders'},{label:'About',href:'#about'},{label:'FAQ',href:'#faq'},{label:'Contact',href:'#contact'}],
  socialLinks: {instagram:{url:'#',label:'Instagram'},facebook:{url:'#',label:'Facebook'},whatsapp:{url:'https://wa.me/918100656258',label:'WhatsApp'}},
  heroHighlights: [], trustItems: [], faqItems: [], sectionCopy: {}
};
let sections = {}; let sectionOrder = []; let customCSS = ''; let livePushed = {settings:false,theme:false,products:false,sections:false,css:false};

async function init(){
  setupSmoothScroll(); setupMobileNav(); setupAutoHideHeader(); setupAccordions(); setupModal(); updateYear(); setupReveal(); setupEnquiryForm();
  await Promise.allSettled([loadSettings(),loadProducts(),loadTheme(),loadSections(),loadCustomCSS()]);
  applySiteSettings(); applyTheme(); applySectionVisibility(); applySectionOrder(); applyNavigation(); applySEO(); applyCustomCSS(); renderProducts(products); setupFilterButtons(); setupCollectionToggle(); applyCollapse();
}
async function loadProducts(){
  try{
    const r=await fetch('content/products.json',{cache:'no-store'});
    if(!r.ok) throw new Error('Catalogue unavailable: HTTP '+r.status);
    const d=await r.json();
    if(!Array.isArray(d.products)||d.products.length===0) throw new Error('No products published');
    if(!livePushed.products) products=d.products;
    /* Internal naming QA must never block customers from seeing the catalogue. */
    if(window.JHALARNaming){
      fetch('content/product-naming.json',{cache:'no-store'})
        .then(x=>x.ok?x.json():null)
        .then(registry=>{
          if(!registry) return;
          const review=window.JHALARNaming.validateCatalogue(d,registry);
          if(review.errors.length||review.reviewCount) console.warn('Catalogue naming QA:',review);
        }).catch(()=>{});
    }
  }catch(e){
    console.error('Product loading failed:',e);
    if(!livePushed.products) products=[];
  }
}
async function loadSettings(){try{const r=await fetch('content/site-settings.json');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(!livePushed.settings)settings=Object.assign({},settings,d);}catch(e){console.warn('Settings fallback',e);}}
async function loadTheme(){try{const r=await fetch('content/theme.json');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(!livePushed.theme)theme=Object.assign({},theme,d);}catch(e){console.warn('Theme fallback',e);}}
async function loadSections(){try{const r=await fetch('content/sections.json');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(!livePushed.sections){sections=d.sections||{};sectionOrder=Array.isArray(d.order)?d.order:[];}}catch(e){console.warn('Sections fallback',e);if(!livePushed.sections){document.querySelectorAll('[data-section]').forEach(el=>sections[el.dataset.section]={visible:true});sectionOrder=[...document.querySelectorAll('[data-section]')].map(el=>el.dataset.section);}}}
async function loadCustomCSS(){try{const r=await fetch('content/custom-css.json');if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();if(!livePushed.css)customCSS=d.css||'';}catch(e){customCSS='';}}
function applyTheme(){const root=document.documentElement;if(theme.colors)Object.entries(theme.colors).forEach(([k,v])=>v&&root.style.setProperty(k,v));if(theme.fonts){if(theme.fonts.heading)root.style.setProperty('--font-heading',theme.fonts.heading);if(theme.fonts.body)root.style.setProperty('--sans',theme.fonts.body);}if(theme.layout){const l=theme.layout;if(l.sectionY)root.style.setProperty('--section-y',l.sectionY);if(l.cardRadius)root.style.setProperty('--radius-lg',l.cardRadius);if(l.containerWidth)root.style.setProperty('--container',l.containerWidth);if(l.headerHeight)root.style.setProperty('--header-h',l.headerHeight);if(l.buttonRadius)root.style.setProperty('--button-radius',l.buttonRadius);if(l.shadowIntensity)root.style.setProperty('--shadow-alpha',l.shadowIntensity);if(l.headingWeight)root.style.setProperty('--heading-weight',l.headingWeight);if(l.headingTracking)root.style.setProperty('--heading-tracking',l.headingTracking);if(l.headingLeading)root.style.setProperty('--heading-leading',l.headingLeading);if(l.bodyWeight)root.style.setProperty('--body-weight',l.bodyWeight);if(l.bodyTracking)root.style.setProperty('--body-tracking',l.bodyTracking);if(l.bodyLeading)root.style.setProperty('--body-leading',l.bodyLeading);if(l.cardPad)root.style.setProperty('--card-pad',l.cardPad);if(l.gridGap)root.style.setProperty('--grid-gap',l.gridGap);if(l.sectionHeaderGap)root.style.setProperty('--section-header-gap',l.sectionHeaderGap);if(l.sectionAlign)root.style.setProperty('--section-align',l.sectionAlign);if(l.productGap)root.style.setProperty('--product-gap',l.productGap);if(l.splitGap)root.style.setProperty('--split-gap',l.splitGap);if(l.processGap)root.style.setProperty('--process-gap',l.processGap);if(l.contactGap)root.style.setProperty('--contact-gap',l.contactGap);if(l.faqGap)root.style.setProperty('--faq-gap',l.faqGap);if(l.footerGap)root.style.setProperty('--footer-gap',l.footerGap);if(l.productPad)root.style.setProperty('--product-pad',l.productPad);if(l.faqPad)root.style.setProperty('--faq-pad',l.faqPad);if(l.footerPad)root.style.setProperty('--footer-pad',l.footerPad);if(l.trustPad)root.style.setProperty('--trust-pad',l.trustPad);root.style.setProperty('--grid-min',l.productColumns==='2'?'380px':(l.productColumns==='4'?'260px':'300px'));}const mt=document.querySelector('meta[name="theme-color"]');if(mt&&theme.colors?.['--brand-primary'])mt.content=theme.colors['--brand-primary'];applyRevealMode();}
function esc(s){return String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function applySectionVisibility(){document.querySelectorAll('[data-section]').forEach(el=>{const s=sections[el.dataset.section];el.style.display=(s&&s.visible===false)?'none':'';});}
function applySectionOrder(){const main=document.querySelector('main');if(!main||!Array.isArray(sectionOrder)||!sectionOrder.length)return;sectionOrder.forEach(k=>{const el=main.querySelector(`[data-section="${k}"]`);if(el)main.appendChild(el);});}
function applyCustomCSS(){let el=document.getElementById('jhalar-custom-css');if(!el){el=document.createElement('style');el.id='jhalar-custom-css';document.head.appendChild(el);}el.textContent=customCSS||'';}
function applyNavigation(){const nav=document.querySelector('.clean-nav');if(nav&&settings.navItems?.length)nav.innerHTML=settings.navItems.slice(0,3).map(n=>`<a href="${esc(n.href)}">${esc(n.label)}</a>`).join('');const mobile=document.getElementById('mobile-nav');if(mobile&&settings.navItems?.length){const extra=(settings.footerNavItems||[]).filter(n=>!settings.navItems.some(x=>x.href===n.href));mobile.innerHTML=[...settings.navItems,...extra].map(n=>`<a href="${esc(n.href)}" class="mobile-link">${esc(n.label)}</a>`).join('');}const footerList=document.querySelector('.footer-links ul');if(footerList&&settings.footerNavItems)footerList.innerHTML=settings.footerNavItems.map(n=>`<li><a href="${esc(n.href)}">${esc(n.label)}</a></li>`).join('')+'<li><a href="privacy.html">Privacy Policy</a></li>';const social=document.querySelector('.footer-social ul');if(social&&settings.socialLinks){social.innerHTML='';for(const k of ['instagram','facebook','whatsapp']){const s=settings.socialLinks[k];if(s&&s.url&&s.url!=='#')social.innerHTML+=`<li><a href="${esc(s.url)}" target="_blank" rel="noopener"><i class="fab fa-${k}"></i> ${esc(s.label||k)}</a></li>`;}}}
function applySEO(){if(settings.siteTitle)document.title=settings.siteTitle;if(settings.siteDescription){for(const sel of ['meta[name="description"]','meta[property="og:description"]','meta[name="twitter:description"]']){const m=document.querySelector(sel);if(m)m.content=settings.siteDescription;}}if(settings.ogImage){const img=settings.ogImage.startsWith('http')?settings.ogImage:'https://lokeshdugar040.github.io/jhalar-hanging-decor/'+settings.ogImage;for(const sel of ['meta[property="og:image"]','meta[name="twitter:image"]']){const m=document.querySelector(sel);if(m)m.content=img;}}}
function renderProducts(list){const grid=document.getElementById('product-grid');if(!grid)return;if(!list?.length){grid.innerHTML='<p class="catalogue-error">Catalogue temporarily unavailable. Please reload the page.</p>';return;}grid.innerHTML=list.map(p=>`<article class="product-card" data-category="${esc(p.category)}" data-product-id="${esc(p.id)}"><div class="product-image"><img src="${esc(p.image)}" alt="${esc(p.title)} — ${esc(p.category)}" width="1080" height="1080" loading="lazy" decoding="async"></div><div class="product-info"><span class="product-category">${esc(p.category)}</span><h3 class="product-title">${esc(p.title)}</h3><p class="product-desc">${esc(p.description)}</p><button class="btn btn-primary product-details-btn" data-product-id="${esc(p.id)}" aria-label="View details for ${esc(p.title)}">View details</button></div></article>`).join('');grid.querySelectorAll('.product-details-btn').forEach(b=>b.addEventListener('click',()=>openProductModal(Number(b.dataset.productId))));applyCollapse();}
let PREVIEW_COUNT=6,collectionExpanded=false,activeCategory='all';
function applyCollapse(){const grid=document.getElementById('product-grid'),btn=document.getElementById('collection-toggle');if(!grid||!btn)return;const cards=[...grid.querySelectorAll('.product-card:not(.is-filtered-out)')],can=activeCategory==='all'&&cards.length>PREVIEW_COUNT,hidden=can&&!collectionExpanded;cards.forEach((c,i)=>c.classList.toggle('is-collapsed',hidden&&i>=PREVIEW_COUNT));if(can){btn.hidden=false;btn.textContent=collectionExpanded? 'Show fewer':`View all ${cards.length} products`;btn.setAttribute('aria-expanded',String(collectionExpanded));}else btn.hidden=true;}
function setupCollectionToggle(){const btn=document.getElementById('collection-toggle');if(btn)btn.addEventListener('click',()=>{collectionExpanded=!collectionExpanded;applyCollapse();if(!collectionExpanded)document.getElementById('collection')?.scrollIntoView({behavior:'smooth',block:'start'});});}
function setupFilterButtons(){const btns=[...document.querySelectorAll('.filter-btn')];if(!btns.length)return;const cats=new Set(products.map(p=>p.category));btns.forEach(b=>{b.hidden=b.dataset.filter!=='all'&&!cats.has(b.dataset.filter);if(b.dataset.bound)return;b.dataset.bound='1';b.addEventListener('click',()=>{btns.forEach(x=>{x.classList.remove('active');x.setAttribute('aria-selected','false')});b.classList.add('active');b.setAttribute('aria-selected','true');filterProducts(b.dataset.filter);});});const active=btns.find(b=>b.classList.contains('active')&&!b.hidden)||btns.find(b=>b.dataset.filter==='all');if(active)filterProducts(active.dataset.filter);}
function filterProducts(cat){activeCategory=cat||'all';collectionExpanded=activeCategory!=='all';document.querySelectorAll('.product-card').forEach(c=>c.classList.toggle('is-filtered-out',!(cat==='all'||c.dataset.category===cat)));applyCollapse();}
function closeMobileNav(){const t=document.querySelector('.mobile-toggle'),n=document.getElementById('mobile-nav'),h=document.querySelector('.site-header');n?.classList.remove('open');t?.setAttribute('aria-expanded','false');h?.classList.remove('nav-open');}
function setupMobileNav(){const t=document.querySelector('.mobile-toggle'),n=document.getElementById('mobile-nav');if(!t||!n)return;t.addEventListener('click',()=>{const open=t.getAttribute('aria-expanded')==='true';t.setAttribute('aria-expanded',String(!open));n.classList.toggle('open');document.querySelector('.site-header')?.classList.toggle('nav-open',!open);});n.addEventListener('click',e=>{if(e.target.closest('a'))closeMobileNav();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMobileNav();});window.addEventListener('resize',()=>{if(innerWidth>900)closeMobileNav();});}
function setupSmoothScroll(){document.addEventListener('click',e=>{const a=e.target.closest('a[href^="#"]');if(!a)return;const el=document.querySelector(a.getAttribute('href'));if(!el)return;e.preventDefault();el.scrollIntoView({behavior:'smooth',block:'start'});});}
function setupAutoHideHeader(){const h=document.querySelector('.site-header');if(!h)return;let last=scrollY;ticking=false;window.addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const y=scrollY;if(Math.abs(y-last)>8){h.classList.toggle('scrolled',y>12);if(y>last+10&&!document.getElementById('mobile-nav')?.classList.contains('open'))h.classList.add('header-hidden');if(y<last-10)h.classList.remove('header-hidden');last=y;}ticking=false;});},{passive:true});}
function openProductModal(id){const p=products.find(x=>Number(x.id)===Number(id));if(!p)return;const overlay=document.getElementById('product-modal');if(!overlay)return;document.getElementById('modal-photo').src=p.image;document.getElementById('modal-photo').alt=p.title;document.getElementById('modal-category').textContent=p.category;document.getElementById('modal-title').textContent=p.title;document.getElementById('modal-desc').textContent=p.description;const wa=document.getElementById('modal-wa-btn');if(wa){wa.href=`https://wa.me/${settings.whatsapp}?text=${encodeURIComponent('Hello JHALAR, I am interested in '+p.title+'.')}`;}overlay.hidden=false;overlay.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');}
function setupModal(){const overlay=document.getElementById('product-modal');if(!overlay)return;overlay.addEventListener('click',e=>{if(e.target.closest('#modal-close')||e.target===overlay||e.target.classList.contains('modal-backdrop')){overlay.hidden=true;overlay.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!overlay.hidden){overlay.hidden=true;overlay.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');}});}
function setupAccordions(){document.querySelectorAll('.accordion-header').forEach(b=>b.addEventListener('click',()=>{const open=b.getAttribute('aria-expanded')==='true';b.setAttribute('aria-expanded',String(!open));const c=document.getElementById(b.getAttribute('aria-controls'));if(c)c.hidden=open;}));}
function setupReveal(){if(!('IntersectionObserver' in window)){document.querySelectorAll('.reveal').forEach(x=>x.classList.add('revealed'));return;}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('revealed');io.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(x=>io.observe(x));}
function applyRevealMode(){if(theme.layout?.revealAnimation===false)document.querySelectorAll('.reveal').forEach(x=>x.classList.add('revealed'));}
function setupEnquiryForm(){const f=document.getElementById('enquiry-form');if(!f)return;f.addEventListener('submit',e=>{e.preventDefault();const fd=new FormData(f);const parts=[`Name: ${fd.get('name')}`,`Buyer type: ${fd.get('buyer-type')}`,`Phone: ${fd.get('phone')}`,`Email: ${fd.get('email')||''}`,`City/State: ${fd.get('location')}`,`Company: ${fd.get('company')||''}`,`Need: ${fd.get('category')}`,`Quantity: ${fd.get('quantity')||''}`,`Date: ${fd.get('date')||''}`,`Details: ${fd.get('details')||''}`];window.open(`https://wa.me/${settings.whatsapp}?text=${encodeURIComponent('Hello JHALAR, I would like to enquire.\n\n'+parts.join('\n'))}`,'_blank','noopener');});}
function updateYear(){const y=document.getElementById('current-year');if(y)y.textContent=new Date().getFullYear();}

document.addEventListener('DOMContentLoaded',init);
